version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes: 
      - ../docker-volumes/postgres/db:/var/lib/postgresql/data