import { GithubRepo, GithubUser, Owner } from "../../types/github";

export const mockUser: GithubUser = {
  login: "myf1996",
  id: 1,
  avatar_url: "https://api.github.com/avatar",
  gravatar_id: "",
  url: "https://api.github.com",
  html_url: "https://api.github.com/html",
  followers_url: "https://api.github.com/followers",
  following_url: "https://api.github.com/following",
  gists_url: "https://api.github.com/gists",
  starred_url: "https://api.github.com/starred",
  subscriptions_url: "https://api.github.com/subscriptions",
  organizations_url: "https://api.github.com/orgs",
  repos_url: "https://api.github.com/repos",
  events_url: "https://api.github.com/events",
  received_events_url: "https://api.github.com/received_events",
  type: "User",
  site_admin: false,
  name: "Test User",
  company: "Test Company",
  blog: "https://api.github.com/blog",
  location: "Test Location",
  email: "test@example.com",
  hireable: null,
  bio: "Test bio",
  twitter_username: "myf1996",
  public_repos: 10,
  public_gists: 5,
  followers: 100,
  following: 50,
  created_at: new Date(),
  updated_at: new Date(),
  languages: [],
};

export const mockOwner: Owner = {
  login: "myf1996",
  id: 1,
  node_id: "node1",
  avatar_url: "https://api.github.com/avatar",
  gravatar_id: "",
  url: "https://api.github.com",
  html_url: "https://api.github.com/html",
  followers_url: "https://api.github.com/followers",
  following_url: "https://api.github.com/following",
  gists_url: "https://api.github.com/gists",
  starred_url: "https://api.github.com/starred",
  subscriptions_url: "https://api.github.com/subscriptions",
  organizations_url: "https://api.github.com/orgs",
  repos_url: "https://api.github.com/repos",
  events_url: "https://api.github.com/events",
  received_events_url: "https://api.github.com/received_events",
  type: "User",
  site_admin: false,
};

export const mockLanguages: string[] = ["JavaScript", "TypeScript"];

export const mockRepoLanguages = {
  JavaScript: 10000,
  TypeScript: 5000,
};;

export const mockRepos: GithubRepo[] = [
  {
    id: 1,
    node_id: "node1",
    name: "LS-Github-CLI",
    full_name: "testuser/LS-Github-CLI",
    private: false,
    html_url: "https://api.github.com/LS-Github-CLI",
    description: "Test repo 1",
    fork: false,
    url: "https://api.github.com/LS-Github-CLI",
    forks_url: "https://api.github.com/LS-Github-CLI/forks",
    keys_url: "https://api.github.com/LS-Github-CLI/keys",
    collaborators_url: "https://api.github.com/LS-Github-CLI/collaborators",
    teams_url: "https://api.github.com/LS-Github-CLI/teams",
    hooks_url: "https://api.github.com/LS-Github-CLI/hooks",
    issue_events_url: "https://api.github.com/LS-Github-CLI/issues/events",
    events_url: "https://api.github.com/LS-Github-CLI/events",
    assignees_url: "https://api.github.com/LS-Github-CLI/assignees",
    branches_url: "https://api.github.com/LS-Github-CLI/branches",
    tags_url: "https://api.github.com/LS-Github-CLI/tags",
    blobs_url: "https://api.github.com/LS-Github-CLI/blobs",
    git_tags_url: "https://api.github.com/LS-Github-CLI/git/tags",
    git_refs_url: "https://api.github.com/LS-Github-CLI/git/refs",
    trees_url: "https://api.github.com/LS-Github-CLI/trees",
    statuses_url: "https://api.github.com/LS-Github-CLI/statuses",
    languages_url: 
      "https://api.github.com/repos/myf1996/LS-Github-CLI/languages",
    stargazers_url: "https://api.github.com/LS-Github-CLI/stargazers",
    contributors_url: "https://api.github.com/LS-Github-CLI/contributors",
    subscribers_url: "https://api.github.com/LS-Github-CLI/subscribers",
    subscription_url: "https://api.github.com/LS-Github-CLI/subscription",
    commits_url: "https://api.github.com/LS-Github-CLI/commits",
    git_commits_url: "https://api.github.com/LS-Github-CLI/git/commits",
    comments_url: "https://api.github.com/LS-Github-CLI/comments",
    issue_comment_url: "https://api.github.com/LS-Github-CLI/issues/comments",
    contents_url: "https://api.github.com/LS-Github-CLI/contents",
    compare_url: "https://api.github.com/LS-Github-CLI/compare",
    merges_url: "https://api.github.com/LS-Github-CLI/merges",
    archive_url: "https://api.github.com/LS-Github-CLI/archive",
    downloads_url: "https://api.github.com/LS-Github-CLI/downloads",
    issues_url: "https://api.github.com/LS-Github-CLI/issues",
    pulls_url: "https://api.github.com/LS-Github-CLI/pulls",
    milestones_url: "https://api.github.com/LS-Github-CLI/milestones",
    notifications_url: "https://api.github.com/LS-Github-CLI/notifications",
    labels_url: "https://api.github.com/LS-Github-CLI/labels",
    releases_url: "https://api.github.com/LS-Github-CLI/releases",
    deployments_url: "https://api.github.com/LS-Github-CLI/deployments",
    created_at: new Date(),
    updated_at: new Date(),
    pushed_at: new Date(),
    git_url: "git://example.com/LS-Github-CLI",
    ssh_url: "ssh://example.com/LS-Github-CLI",
    clone_url: "https://api.github.com/LS-Github-CLI.git",
    svn_url: "https://api.github.com/LS-Github-CLI",
    homepage: "https://api.github.com/LS-Github-CLI",
    size: 1234,
    stargazers_count: 100,
    watchers_count: 100,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 10,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 5,
    license: "MIT",
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    visibility: "public",
    forks: 10,
    open_issues: 5,
    watchers: 100,
    default_branch: "main",
    owner: mockOwner,
    repo_languages: [],
    topics: [],
    user_id: 1,
  },
];
